AWSTemplateFormatVersion: "2010-09-09"
Description: "This example template shows how to create a standard SQS queue."

Resources:
  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      FifoQueue: true
      QueueName: "Queue.fifo"
